# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/specify-string.js
#####

SDLC_SPECIFY_STRING_JS:=$(DIST)/specify-string.js
SDLC_SPECIFY_STRING_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(SDLC_SPECIFY_STRING_JS)

$(SDLC_SPECIFY_STRING_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_SPECIFY_STRING_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/specify-string.js
#####
